"""
pdf_generator.py — Converts Markdown travel plans into branded PDF documents.

Uses markdown + xhtml2pdf (pisa) for HTML→PDF conversion with the
Navy + Gold brand palette.
"""

from __future__ import annotations
import io
import markdown as md


def generate_pdf(markdown_content: str) -> bytes:
    """
    Convert a Markdown string into a styled PDF (bytes).

    The PDF uses the project's Navy (#001F3F) + Gold (#FFD700) palette
    with a branded header and footer.
    """
    try:
        from xhtml2pdf import pisa
    except ImportError:
        raise ImportError(
            "xhtml2pdf is required for PDF generation. "
            "Install it with: pip install xhtml2pdf"
        )

    body_html = md.markdown(
        markdown_content,
        extensions=["tables", "fenced_code", "nl2br"],
    )

    full_html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<style>
    @page {{
        size: A4;
        margin: 2cm 2cm 3cm 2cm;

        @frame footer {{
            -pdf-frame-content: page-footer;
            bottom: 0.5cm;
            margin-left: 2cm;
            margin-right: 2cm;
            height: 1.5cm;
        }}
    }}

    body {{
        font-family: Helvetica, Arial, sans-serif;
        font-size: 11px;
        color: #222;
        line-height: 1.6;
    }}

    .header {{
        background-color: #001F3F;
        color: #FFD700;
        padding: 16px 24px;
        margin: -2cm -2cm 24px -2cm;
        font-size: 20px;
        font-weight: bold;
        letter-spacing: 1px;
    }}
    .header small {{
        font-size: 11px;
        color: #ccc;
        font-weight: normal;
        display: block;
        margin-top: 4px;
    }}

    h1 {{ color: #001F3F; font-size: 18px; border-bottom: 2px solid #FFD700; padding-bottom: 4px; }}
    h2 {{ color: #001F3F; font-size: 15px; margin-top: 18px; }}
    h3 {{ color: #333; font-size: 13px; }}

    table {{
        width: 100%;
        border-collapse: collapse;
        margin: 12px 0;
    }}
    th {{
        background-color: #001F3F;
        color: #FFD700;
        padding: 6px 10px;
        text-align: left;
        font-size: 10px;
    }}
    td {{
        border-bottom: 1px solid #ddd;
        padding: 5px 10px;
        font-size: 10px;
    }}
    tr:nth-child(even) td {{ background-color: #f8f8f8; }}

    code {{
        background: #f0f0f0;
        padding: 1px 4px;
        font-size: 10px;
        border-radius: 3px;
    }}

    ul, ol {{ padding-left: 20px; }}
    li {{ margin-bottom: 3px; }}

    hr {{ border: none; border-top: 1px solid #FFD700; margin: 16px 0; }}
</style>
</head>
<body>
    <div class="header">
        ✈ Mustafa AI Travel Concierge
        <small>Your Personalised Travel Plan</small>
    </div>

    {body_html}

    <div id="page-footer" style="text-align: center; font-size: 8px; color: #999;">
        Generated by Mustafa AI Travel Concierge · All plans should be verified independently.
    </div>
</body>
</html>"""

    buffer = io.BytesIO()
    pisa_status = pisa.CreatePDF(full_html, dest=buffer)

    if pisa_status.err:
        raise RuntimeError(f"PDF generation failed with {pisa_status.err} errors.")

    return buffer.getvalue()
